<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */
global $wp_query, $thisPageType;

//* Remove default loop
remove_action( 'genesis_loop', 'genesis_404' );
$args = array(
    'name'        => '404page',
    'post_type'   => 'page',
    'post_status' => 'publish',
    'numberposts' => 1
);

$wp_query = new WP_Query($args);
$wp_query->is_404 = true;
$wp_query->is_page = true;
genesis();